import fs from 'fs';

const base64 = fs.readFileSync('dist/microvium.wasm').toString('base64');

const s = `
// Note: this file is auto-generated by scripts/output-base64.mjs which is invoked from the build script
export const microviumWasmBase64: string = "${base64}";
`;
fs.writeFileSync('src/microvium-wasm-base64.ts', s);