
// THIS FILE IS AUTO-GENERATED BY scripts/extract-memory-stats-layout.mjs

export const memoryStatsFields = ["totalSize", "fragmentCount", "coreSize", "importTableSize", "globalVariablesSize", "registersSize", "stackHeight", "stackAllocatedCapacity", "stackHighWaterMark", "virtualHeapUsed", "virtualHeapHighWaterMark", "virtualHeapAllocatedCapacity"];

export interface MemoryStats {
  totalSize: number;
  fragmentCount: number;
  coreSize: number;
  importTableSize: number;
  globalVariablesSize: number;
  registersSize: number;
  stackHeight: number;
  stackAllocatedCapacity: number;
  stackHighWaterMark: number;
  virtualHeapUsed: number;
  virtualHeapHighWaterMark: number;
  virtualHeapAllocatedCapacity: number;
}
